server:
  port: 6003
spring:
  cloud:
    gateway:
      routes:
        - id: address-services
          uri: http://localhost:6000/
          Predicates:
            - Path=/serviceA/**
        - id: employee-services
          uri: http://localhost:6001/
          Predicates:
            - Path=/serviceB/**